### ISSUE TITLE
多串口通信问题

### ISSUE THREAD

**Issue by geohuz** [king2088/cordova-plugin-usbserialport#1]
请问该插件支持通过usb hub支持多路串口通信吗.

**Comment by king2088** [comment]
> 请问该插件支持通过usb hub支持多路串口通信吗.
感谢你的关注，此插件并不支持多路串口通信

**Comment by geohuz** [comment]
请问有什么建议吗, 如果需要这方面的功能, 我看到上游库里的文档里是有这个的 https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#Feature_Matrix , Can I open multiple connections in one application? 这段, 是否可以通过简单的修改达到目标? 谢谢
