### ISSUE TITLE
android@11 

### ISSUE THREAD

**Issue by mgltuba** [king2088/cordova-plugin-usbserialport#2]
hello i'm using this plugin on ionic V6 but i need publish goolge playstore but minimum requirment android sdk 31. This plugin working cordova android@9 working good, but cordova android@11 running force quit and give 
###error
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
                                                                                                    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
                                                                                                    	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)

pls how to fix this error

**Comment by king2088** [comment]
I don't know much about the new version of Android. Maybe you can find the answer here https://stackoverflow.com/questions/69037481/android-app-wont-build-the-mincompilesdk-31-specified-in-a-dependencys-an

**Comment by mgltuba** [comment]
serial.java 
line 203
	PendingIntent pendingIntent = PendingIntent.getBroadcast(cordova.getActivity(), 0, new Intent(UsbBroadcastReceiver.USB_PERMISSION), 
					PendingIntent.FLAG_MUTABLE | PendingIntent.FLAG_UPDATE_CURRENT);
working

**Comment by king2088** [comment]
> serial.java line 203 PendingIntent pendingIntent = PendingIntent.getBroadcast(cordova.getActivity(), 0, new Intent(UsbBroadcastReceiver.USB_PERMISSION), PendingIntent.FLAG_MUTABLE | PendingIntent.FLAG_UPDATE_CURRENT); working

Great!

**Comment by H31nz3l** [comment]
Just made an pull request that fixes this error in the library

**Comment by king2088** [comment]
> Just made an pull request that fixes this error in the library

Thx.
